#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)
fcitx
export LANG=ja_JP.UTF-8
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
export DefaultIMModule=fcitx 


if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrandr --output VIRTUAL1 --off --output eDP2 --mode 2880x1620 --pos 0x0 --rotate normal --output DP1 --mode 2560x1440 --pos 2880x0 --rotate normal --output DP2 --off --output HDMI2 --off --output HDMI1 --off --output VGA1 --off

# Xresourcesの設定を有効にする
xrdb -merge ~/.Xresources

exec awesome
